### ISSUE TITLE
Changing bullet size: not aligned to the line

### ISSUE THREAD

**Issue by trinhngocthuyen** [edekhayser/Timeline#10]
I tried changing the bullet size from (14, 14) to (30, 30) and got an unexpected result as follow.
I think the bullets and the line should be automatically center-aligned.
![change size](https://cloud.githubusercontent.com/assets/8844044/7130212/2a863c04-e296-11e4-9150-a25be59f9539.png)
![result](https://cloud.githubusercontent.com/assets/8844044/7130213/2eae139c-e296-11e4-88e4-0fd4b5e190b8.png)

**Comment by edekhayser** [comment]
This control uses fixed constants for the size of the bullet and the
position of the line. If you want to change one, you will have to change
another.

One solution you could have is to change the line's x-coordinate equal to
the bullet's x-coordinate + the bullet's width / 2.

In future versions, I may allow the bullet (and the line) to be more
resizable.

**Comment by edekhayser** [comment]
Also, the lines' heights and starting Y coordinate must also be considered.
I recommend using the predefined sizes at least for now.
