### ISSUE TITLE
Warning: Attempt to present whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by AppsCodeCamp** [edekhayser/Timeline#11]
Hello, im about trying to zoom the image when tapped, but it says 2015-08-07 19:35:59.143 Conferencia[10216:2712164] Warning: Attempt to present <JTSImageViewController: 0x14f034600> on <Conferencia.ViewController: 0x14ed12370> whose view is not in the window hierarchy!
 
I checked all and the method inside timeline.swift is being called. What else should i put? another viewcontroller for the image zoomed? 

Thanks

**Comment by edekhayser** [comment]
I'm not sure why you are getting this error. Does everything look correct from the user's perspective? Also, make sure that the timeline is on screen when this is called.

**Comment by AppsCodeCamp** [comment]
Yeah, the timeline is on the screen, the photos too, but when i tap on the photo it says me an error on the  terminal. Do i need to do anything else? Like a segue or anything? 

Thanks

**Comment by edekhayser** [comment]
The only other thing that I can think of is that you are using a different version of JTSImageViewController?

**Comment by AppsCodeCamp** [comment]
Im using the swift 1.2 one as im using xcode 6.4 atm

**Comment by edekhayser** [comment]
@AppsCodeCamp Did you ever find a way to resolve this issue?
