### ISSUE TITLE
Supporting Right Alignment

### ISSUE THREAD

**Issue by Hussein75** [edekhayser/Timeline#12]
Hello, I like your Timeline view and I was searching for it, I already use it, but if you can support putting bullets in right ( for supporting Right-to-Left languages like Arabic ).

By adding a new variable to choose the alignment of the Timeline ( Right or Left ).

**Comment by edekhayser** [comment]
I will look into this when I get a chance.

**Comment by Hussein75** [comment]
I'll appreciate if you do this, because I need it in my projects..

**Comment by edekhayser** [comment]
The newest version has a new `showBulletOnRight` variable. Set this to true to have RTL
