### ISSUE TITLE
Cannot run under xcode 6

### ISSUE THREAD

**Issue by LawrenceHan** [edekhayser/Timeline#13]
### Got a lot of error (red)

<img width="548" alt="screen shot 2015-08-26 at 12 06 56" src="https://cloud.githubusercontent.com/assets/7960810/9485374/0886e9b4-4beb-11e5-8758-49d834b8492c.png">

**Comment by LawrenceHan** [comment]
@edekhayser please have a look :laughing:

**Comment by edekhayser** [comment]
This project is updated to Swift 2.0, which is why you can't use it in Xcode 6. While your changes make compatibility with Xcode 6 possible, it would undo the effort made to update it.
