### ISSUE TITLE
Add UITapGestureRecognizer to TimeFrame struct?

### ISSUE THREAD

**Issue by utkarsh2012** [edekhayser/Timeline#18]
How can I add an onTap action to individual `TimeFrames`?

**Comment by edekhayser** [comment]
This is not possible with the current project, but it wouldn't be hard to add it. 
The changes this would require would be:
- modify TimeFrame to have a property `let gestureRecognizer: UIGestureRecognizer?`
- inside `blockForTimeFrame(_, imageTag:)` add `if let gesture = element.gestureRecognizer { v.addGestureRecognizer(gesture) }`

I have not actually implemented this change, but this should work in theory. Let me know if this works for you, and if so, please send a pull request!

**Comment by utkarsh2012** [comment]
All I needed was: Take an action when someone taps a timeline item. Noticed you have a button on top of every items, so added `button.addTarget(self, action:#selector(handleRegister(sender:)), for: .touchUpInside)` and when its called:

    @objc fileprivate func handleRegister(sender: UIButton){
        onTap!(sender)
    }

`onTap` is passed in the constructor:

    public init(bulletType: BulletType, timeFrames: [TimeFrame], onTap: @escaping (AnyObject) -> ()){
        self.timeFrames = timeFrames
        self.bulletType = bulletType
        self.onTap = onTap
        super.init(frame: CGRect.zero)

        translatesAutoresizingMaskIntoConstraints = false
        
        setupContent()
    }


Can send a PR if you think its the right approach.

**Comment by edekhayser** [comment]
The button is not on every cell, it is on every cell _with an image_. If you are fine with that, then keep your solution, but if you want touch actions to work, go with what I suggested before.

**Comment by utkarsh2012** [comment]
ah yeah, each cell has an image in my case. Thanks for the help! I might need to revisit this and add a Tap gesture. Closing the issue now.
