### ISSUE TITLE
Circle is not working, possibly others also.

### ISSUE THREAD

**Issue by edekhayser** [edekhayser/Timeline#6]

**Comment by yonat** [comment]
Just add this line in private fund circleView():

        circle.setTranslatesAutoresizingMaskIntoConstraints(false)

**Comment by yonat** [comment]
Also, you can make it use a path like the other bullets, using:

    let path = UIBezierPath(ovalInRect: circle.bounds)

**Comment by edekhayser** [comment]
@yonat If you could make a pull request with this fixed, it would be very helpful. I will not be able to fix this myself in at least the next week.

**Comment by edekhayser** [comment]
Thanks @yonat!
