### ISSUE TITLE
JTSImageViewControllerBackgroundStyle_ScaledDimmed Doesn't exist in v. 1.4?

### ISSUE THREAD

**Issue by siegesmund** [edekhayser/Timeline#8]
Throws an error when JTSImageViewController is installed via CocoaPods.

**Comment by edekhayser** [comment]
If you are importing that using CocoaPods, remember to import the module
and not just the file.

**Comment by knikaha** [comment]
just upgrade your xcode

**Comment by knikaha** [comment]
the issue with imageview button when i tapped in gives me error

**Comment by edekhayser** [comment]
I'm closing this because it has to do with a version of a dependency that isn't used in the project, and the issue is over a year old. In the future, I may update the project to use a newer version.
