### ISSUE TITLE
Dynamic Timeframes and Images presentation problems

### ISSUE THREAD

**Issue by BenAraqve** [edekhayser/Timeline#9]
Hey, first of all, thank you for your work it has help me a lot. I have some questions and my instinct said those questions are really stupid but even tho I played with your code I ca't this specific things happen:

How can I paint timeframes dynamically so the image below looks more like one timeframe it's contain in a for loop forin lop etc if you please help me with that

![screen shot 2015-03-02 at 6 36 27 pm](https://cloud.githubusercontent.com/assets/5800601/6453380/4a727200-c10b-11e4-88ce-ffb7d90960ee.png)

And the other question is in the section where you paint the image the imageview dont apply the 10 units in the cornerRadius and how can I make the image be the same size as the container in this specific case backgroundViewForImage?

Thank you very much for your response and sorry if those questions are basic but...

**Comment by edekhayser** [comment]
For the first question, I would imagine that your code would look like this:

```swift
var timeFrames = [TimeFrame]()
for 0...5{
    timeFrames += [TimeFrame(text: "New Year's Day", date: "January 1", image: UIImage(named: "YourImage.png")]
}
timeline = TimelineView(bulletType: .Diamond, timeFrames: timeFrames)
```

About the second question, you might be able to change the image view property in the timeline to be ScaleAspectFill.

**Comment by BenAraqve** [comment]
Hey, Evan, thank you for your response, your first answer help me a lot even tho it was simple way to do it, you should see my code it was lame BUT for your second answer I used all the options you have and even tho I was using a large image the code just center it but didn't placed the image the same size as the container I even try to customize  the NSLayoutConstraints but I can't make that work

**Comment by edekhayser** [comment]
This code is relevant to your issue:

```swift
v.addConstraints([
				NSLayoutConstraint(item: imageView, attribute: .Width, relatedBy: .Equal, toItem: nil, attribute: .NotAnAttribute, multiplier: 1.0, constant: 130),
				NSLayoutConstraint(item: imageView, attribute: .Width, relatedBy: .Equal, toItem: nil, attribute: .NotAnAttribute, multiplier: 1.0, constant: 130),
				NSLayoutConstraint(item: imageView, attribute: .CenterX, relatedBy: .Equal, toItem: backgroundViewForImage, attribute: .CenterX, multiplier: 1.0, constant: 0),
				NSLayoutConstraint(item: imageView, attribute: .CenterY, relatedBy: .Equal, toItem: backgroundViewForImage, attribute: .CenterY, multiplier: 1.0, constant: 0)
				])
```
This can probably be improved, but right now the image is at fixed size. You might have to play around with that.

**Comment by BenAraqve** [comment]
Evan, thank you again for your short response. It would really awesome if you changed your code so the images actually take SacleAspectFit or just the image take the size of it's container because I Played around with the part of the code you give me in the last response and it was really really awfull, so let me know if we can work in a new version of your timeline and thank you very much.

**Comment by edekhayser** [comment]
@BenAraqve I just updated the project so that the image fits the entire container instead of what it was doing before. Let me know if this helped you out.

**Comment by edekhayser** [comment]
I believe that I fixed the issue mentioned here, if I have not, please reopen.
